AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Configuring Cloudfront with Route53, ACM and S3 as Static Website

Parameters:
  
  # pACMCert:
  #   Description: Choose ACM cert for HTTPS
  #   Type: String
  #   Default: 0fe97b8c-4cc8-4a3c-8141-a9949738950e
  
  pDomainName:
    Description: Domain name
    Type: String
    Default: nodehouse2.com

Resources:

  rs3StaBuck:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: statweb1287-site
      WebsiteConfiguration:
        ErrorDocument: error.html
        IndexDocument: index.html

  rs3StaBuckPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref rs3StaBuck
      PolicyDocument: 
        Id: ak-s3staticWebPol
        Version: 2012-10-17
        Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource: !Join 
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref rs3StaBuck
                  - /*
  rAkCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultRootObject: index.html
        Aliases:
          - nodehouse2.com
        CNAMEs:
          - www.nodehouse2.com
        CacheBehaviors:
          - AllowedMethods:
            - GET
            - HEAD
            TargetOriginId: MyS3Origin
              ViewerProtocolPolicy: redirect-to-https
                  PathPattern: Default
        # Comment: "String"
        ContinuousDeploymentPolicyId: "String"
        Enabled: false
        HttpVersion: "String"
        Origins:
          - DomainName: !Ref pDomainName
            Id: MyS3Origin
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
            
      Tags:
        Tags

Outputs:
  StaticWebsiteAddress:
    Description: URL form bucket properties for static website
    Value: !GetAtt rs3StaBuck.WebsiteURL

  # S3BucketSecureURL:
  #   Description: Name of S3 bucket to hold secure website content
  #   Value: !Join 
  #     - ''
  #     - - 'https://'
  #       - !GetAtt 
  #         - rs3StaBuck
  #         - pHostedZoneName