AWSTemplateFormatVersion: 2010-09-09
Description: |
  Auto Scaling, step scaling with launch template and sns

Parameters:

  pVpsId:
    Description: Choose VPC for resources
    Type: AWS::EC2::VPC::Id

  pAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

  pKeyPair:
    Description: KeyPair Name
    Type: AWS::EC2::KeyPair::KeyName

  pSubnets:
    Description: Subnets where EC2 instances are launched
    Type: List<AWS::EC2::Subnet::Id>

  pEmail:
    Description: Email for SNS Topic subscription
    Type: String

Resources:

  rTargScalWebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group to allow SSH and HTTP
      GroupName: TargScal-Web-Sec-Grp
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: TargScal-Web-Sec-Grp
      VpcId: !Ref pVpsId
  
  rTargScalAppLoadBalSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group to allow HTTP
      GroupName: TargScal-AppLoadBal-Sec-Grp
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: TargScal-AppLoadBal-Sec-Grp
      VpcId: !Ref pVpsId

  rTargScalLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Ref pAmiId
        InstanceType: t2.micro
        KeyName: !Ref pKeyPair
        SecurityGroupIds:
          - !GetAtt rTargScalWebSecurityGroup.GroupId
        UserData: !Base64 |
          #!/bin/bash -x
          #update os
          yum update -y
          #install apache server
          yum install -y httpd
          # get private ip address of ec2 instance using instance metadata
          TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` \
          && PRIVATE_IP=`curl -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/local-ipv4`
          # get public ip address of ec2 instance using instance metadata
          TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` \
          && PUBLIC_IP=`curl -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/public-ipv4` 
          # get date and time of server
          DATE_TIME=`date`
          # set all permissions
          chmod -R 777 /var/www/html
          # create a custom index.html file
          echo "<html>
          <head>
              <title> Application Load Balancer</title>
          </head>
          <body>
              <h1>Testing Application Load Balancer</h1>
              <h2>Congratulations! You have created an instance from Launch Template</h2>
              <h3>This web server is launched from the launch template by AK</h3>
              <p>This instance is created at <b>$DATE_TIME</b></p>
              <p>Private IP address of this instance is <b>$PRIVATE_IP</b></p>
              <p>Public IP address of this instance is <b>$PUBLIC_IP</b></p>
          </body>
          </html>" > /var/www/html/index.html
          # start apache server
          systemctl start httpd
          systemctl enable httpd
      LaunchTemplateName: TargScalLaunchTemp
      TagSpecifications:
        - ResourceType: launch-template 
          Tags:
            - Key: Name 
              Value: TargScalLaunchTemp
      VersionDescription: Launch template for step scaling

  rTargScalTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 15
      HealthCheckPath: /
      HealthCheckPort: traffic-port
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 3
      HealthyThresholdCount: 2
      Name: TargScalTargetGroup
      Port: 80
      Protocol: HTTP
      ProtocolVersion: HTTP1
      TargetType: instance
      UnhealthyThresholdCount: 2
      Tags:
        - Key: Name
          Value: TargScalargetGroup
      VpcId: !Ref pVpsId

  rTargScalLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Name: TargScalLoadBalancer
      Scheme: internet-facing
      SecurityGroups:
        - !GetAtt rTargScalAppLoadBalSecurityGroup.GroupId
      Subnets: !Ref pSubnets
      Tags:
        - Key: Name
          Value: TargScalLoadBalancer
      Type: application

  rTargScalLoadBalancerListener1:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions: 
        - Type: forward 
          TargetGroupArn: !Ref rTargScalTargetGroup
      LoadBalancerArn: !Ref rTargScalLoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: arn:aws:acm:us-east-1:355740888737:certificate/0fe97b8c-4cc8-4a3c-8141-a9949738950e

  rTargScalLoadBalancerListener2:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions: 
        - Type: forward 
          TargetGroupArn: !Ref rTargScalTargetGroup
      LoadBalancerArn: !Ref rTargScalLoadBalancer
      Port: 80
      Protocol: HTTP

  rTargScalAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: TargScalAutoScalingGroup
      AvailabilityZones: !GetAZs ''
      DesiredCapacity: '2'
      HealthCheckType: ELB
      LaunchTemplate:
        LaunchTemplateId: !Ref rTargScalLaunchTemplate
        Version: !GetAtt rTargScalLaunchTemplate.LatestVersionNumber
      MaxSize: '4'
      MinSize: '1' 
      TargetGroupARNs:
        - !Ref rTargScalTargetGroup
      NotificationConfigurations: 
        - TopicARN: !Ref rTargScalSNSTopic1
          NotificationTypes:
            - autoscaling:EC2_INSTANCE_LAUNCH
            - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
            - autoscaling:EC2_INSTANCE_TERMINATE
            - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
            - autoscaling:TEST_NOTIFICATION
      MetricsCollection:
        - Metrics: 
          -  GroupMinSize
          -  GroupMaxSize
          -  GroupDesiredCapacity
          -  GroupInServiceInstances
          -  GroupInServiceCapacity
          -  GroupTotalInstances
          Granularity: '1Minute'

        
  rTargScalPolicy:
      Type: AWS::AutoScaling::ScalingPolicy
      Properties:
        AutoScalingGroupName: !Ref rTargScalAutoScalingGroup
        PolicyType: TargetTrackingScaling
        TargetTrackingConfiguration: 
          PredefinedMetricSpecification: 
            PredefinedMetricType: ASGAverageCPUUtilization
          TargetValue: 50.0

  rTargScalSNSTopic1:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: TargScal-SNS-Topic-HighCPU
      Subscription:
        - Endpoint: !Ref pEmail
          Protocol: email
      TopicName: TargScalSNSTopicHighCPU
      Tags:
        - Key: Name
          Value: TargScal-SNS-Topic-HighCPU

  rTargScalSNSTopic2:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: TargScal-SNS-Topic-NormalCPU
      Subscription:
        - Endpoint: !Ref pEmail
          Protocol: email
      TopicName: TargScalSNSTopicNormalCPU
      Tags:
        - Key: Name
          Value: TargScal-SNS-Topic-NormalCPU

  rTargScalAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref rTargScalSNSTopic1
      AlarmDescription: Alarm for Simple auto scaling group
      AlarmName: TargScal-Alarm
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref rTargScalAutoScalingGroup
      EvaluationPeriods: 1
      MetricName: 'CPUUtilization'
      Namespace: AWS/EC2
      OKActions:
        - !Ref rTargScalSNSTopic2
      Period: 10
      Statistic: Average 
      Threshold: 50

  rTargScalEventRule:  
    Type: AWS::Events::Rule
    Properties: 
      Description: Event rule for auto scaling group
      EventPattern:
        source:
          - aws.application-autoscaling
        detail-type:
          - Application Auto Scaling Scaling Activity State Change
      Name: TargScal-Rule
      State: ENABLED
      Targets: 
        - Arn: 
            !GetAtt rTargScalSNSTopic1.TopicArn
          Id: EBR123

  rTargScalRoute53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt rTargScalLoadBalancer.DNSName
        EvaluateTargetHealth: false
        HostedZoneId: Z0980289Z5HKBL3C8FMZ
      Comment: A record for S3 website endpoint - Secondary record
      HostedZoneId: /hostedzone/Z0980289Z5HKBL3C8FMZ
      Name: targscal.nodehouse2.com
      Type: A 

Outputs:
  AppLoadBalURL:
    Value: !Join 
      -  ''
      - -  'https://'
        -  !GetAtt rTargScalLoadBalancer.DNSName