AWSTemplateFormatVersion: 2010-09-09
Description: |
  MySQL database on EC2 instance

Parameters:

  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

  KeyPair:
    Description: Key Pair for EC2 Instance
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  
  rMySQLDBSecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ec2 instance.
      GroupName: ak-ec2-mysqldb-sec-grp
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: "Name"
          Value: "ak-ec2-mysqldb-sec-grp"
      VpcId: vpc-0e0e378595d502111

  rEC2Inst:
      Type: AWS::EC2::Instance
      Properties:
        ImageId: !Ref LatestAmiId
        InstanceType: t2.micro
        KeyName: !Ref KeyPair
        SecurityGroupIds: 
          - !Ref rMySQLDBSecGrp
        Tags: 
          - Key: Name
            Value: WebServer-Altaz
        
        UserData: !Base64 |
          #!/bin/bash -x 
          sudo yum update -y
          sudo yum install -y mariadb-server
          sudo systemctl start mariadb
          sudo systemctl enable mariadb
          sudo systemctl status mariadb

#Outputs: