AWSTemplateFormatVersion: 2010-09-09
Description: |
  Two S3 buckets with Replication

#Parameters:
  
Resources:
  
  ReplicaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal: 
            Service: [s3.amazonaws.com]

  rBucket1:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: rox-1
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      ReplicationConfiguration:
        Role: !GetAtt
          - ReplicaRole
          - Arn
        Rules:
          - Id: Ak-s3-Rep-Rule
            Status: Enabled
            Prefix: ships
            Destination:
              Bucket: 'arn:aws:s3:::xor-1'
              StorageClass: STANDARD
          - Status: Enabled
            Prefix: boats
            Destination:
              Bucket: 'arn:aws:s3:::xor-1'
      Tags:
        - Key: "Name"
          Value: "S3-Rep-Bucket"

  rBucket2:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: xor-1
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: "Name"
          Value: "S3-Rep-Bucket"


#Outputs: