AWSTemplateFormatVersion: 2010-09-09
Description: |
  Two S3 buckets with Replication

#Parameters:
  
Resources:
  
  rBucket1:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: rox-1
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: "Name"
          Value: "S3-Rep-Bucket"

  rBucket2:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: rox-1
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: "Name"
          Value: "S3-Rep-Bucket"

#Outputs: